<img style="float: left; margin: 30px 15px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/d/db/Logo_ITESO_normal.jpg" width="150" height="250" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Alejandro Serrano y Carola Navarro.

**Fecha:** 4 de septiembre del 2023.

**Expediente** : if716821 y if722049.
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: Link con el enlace del repositorio del creador del proyecto

# Tarea 2: Clase 5 Cont Optimización Programación

## Enunciado de tarea (Transcibirlo)
> Descripción de la tarea

### Ejercicio 1:

> 1. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

**Código de solución estudiante 1**

In [3]:
# Código de solución estudiante 1
texto = 'the notion of a lambda function goes all the way back to the origin of computer science'
words = texto.split()  # Divide la cadena en palabras

# Filtra las palabras que tienen menos de 4 letras
eliminate_words = list(filter(lambda word: len(word) <= 4, words))

print(eliminate_words)


['the', 'of', 'a', 'goes', 'all', 'the', 'way', 'back', 'to', 'the', 'of']


**Código de solución estudiante 2**

In [ ]:
# Código de solución estudiante 2
.
.
.
.


### Ejercicio 2:
 
> 2. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

In [6]:
########### Solución 
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
temperatures



array([ 35.97387961,  99.13294268,  92.6178302 ,  99.69549478,
        63.21119535,  73.90387697,  95.50028838,  99.21476553,
        36.98251238, 101.45813729, 100.5917418 ,  89.38159435,
        89.52156589,  83.8084752 ,  28.37990868,  68.75395211,
        45.86132067,  36.58307493,  56.32208365,  33.96219302,
        45.29071318,  74.86289938,  66.51091383,  88.19316186,
        94.26635864,  46.83131624, 109.60744472, 109.68427993,
        44.55796499,  92.84146259])

**Código de solución estudiante 1**

In [7]:
import numpy as np

# Filtrar las temperaturas que están dentro del rango 32 a 80 usando filter
filtered_temperatures = list(filter(lambda temp: 32 <= temp <= 80, temperatures))

# Calcular el porcentaje
percentage = (len(filtered_temperatures) / len(temperatures)) * 100

print(f"Usando filter: El {percentage:.2f}% de las temperaturas están dentro del rango de 32 a 80 grados Fahrenheit.")

Usando filter: El 46.67% de las temperaturas están dentro del rango de 32 a 80 grados Fahrenheit.


In [8]:
# Filtrar las temperaturas que están dentro del rango 32 a 80 usando filtro de vectores
filtered_temperatures_vector = temperatures[(temperatures >= 32) & (temperatures <= 80)]

# Calcular el porcentaje
percentage_vector = (len(filtered_temperatures_vector) / len(temperatures)) * 100

print(f"Usando filtro de vectores: El {percentage_vector:.2f}% de las temperaturas están dentro del rango de 32 a 80 grados Fahrenheit.")

Usando filtro de vectores: El 46.67% de las temperaturas están dentro del rango de 32 a 80 grados Fahrenheit.


**Código de solución estudiante 2**

### Ejercicio 3:

> 3. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations

>> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

In [9]:
########### Solución 5
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)


[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


**Código de solución estudiante 1**

In [12]:
# Encontrar la esquina inferior izquierda
lower_left_corner = np.minimum.reduce(point_xy)

lower_left_corner

array([0, 2])

**Código de solución estudiante 2**

### Ejercicio 4:

> 4. Find all of the numbers from 1-1000 that are divisible by 7

**Código de solución estudiante 1**

In [13]:

# Lista de números
number = np.arange(1, 1001)

# Resultado usando for tradicional
numbers_divisible_by_7_for = []
for num in number:
    if num % 7 == 0:
        numbers_divisible_by_7_for.append(num)
print("Resultado usando for tradicional:", numbers_divisible_by_7_for)

# Resultado usando compresión de listas
numbers_divisible_by_7_list_comprehension = [num for num in number if num % 7 == 0]
print("Resultado usando compresión de listas:", numbers_divisible_by_7_list_comprehension)

# Resultado usando la función filter
numbers_divisible_by_7_filter = list(filter(lambda num: num % 7 == 0, number))
print("Resultado usando la función filter:", numbers_divisible_by_7_filter)


Resultado usando for tradicional: [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]
Resultado usando compresión de listas: [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 

**Código de solución estudiante 2**